import streamlit as st
import requests
import openai

# Set API keys (replace with your actual keys)
MIDJOURNEY_API_URL = "https://api.midjourney.com/generate"
MIDJOURNEY_API_KEY = "your_midjourney_api_key"
OPENAI_API_KEY = "your_openai_api_key"

# Configure OpenAI API
openai.api_key = OPENAI_API_KEY

# Streamlit UI
st.title("🎨 AI Image Generator (Midjourney & DALL·E)")

# User selects model
model_choice = st.radio("Choose an AI model:", ["Midjourney", "DALL·E"])

# User input for prompt
prompt = st.text_area("Enter your image description:", "A futuristic city skyline at sunset")

# Button to generate image
if st.button("Generate Image"):
    with st.spinner("Generating... Please wait ⏳"):

        if model_choice == "Midjourney":
            # Call Midjourney API
            response = requests.post(
                MIDJOURNEY_API_URL,
                json={"prompt": prompt},
                headers={"Authorization": f"Bearer {MIDJOURNEY_API_KEY}"},
            )
            if response.status_code == 200:
                image_url = response.json().get("image_url")
                st.image(image_url, caption="Generated by Midjourney", use_column_width=True)
            else:
                st.error("Failed to generate image with Midjourney.")

        elif model_choice == "DALL·E":
            # Call OpenAI's DALL·E API
            response = openai.Image.create(prompt=prompt, n=1, size="1024x1024")
            if "data" in response:
                image_url = response["data"][0]["url"]
                st.image(image_url, caption="Generated by DALL·E", use_column_width=True)
            else:
                st.error("Failed to generate image with DALL·E.")


